name: deszipando
on:
  schedule:
    - cron: '* 09 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: BAIXANDO
      run: |

          unzip brplay.zip -d /usr/bin/bash/brplayfinal            
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "TÁ DESZIPADO MEU IRMÃO"
        git push
