name: zipando again
on:
  schedule:
    - cron: '* 09 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: BAIXANDO
      run: |
             wget -r https://live-as-10-16.video.globo.com/d/s/hls-globo-go01/hls-globo-go01_655/playlist.m3u8


       
       
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
